### ISSUE TITLE
Participants registered for events not displayed correctly

### ISSUE THREAD

**Issue by opowell26** [GTBitsOfGood/enchanted-closet#196]
Participants that are registered for an event are not displayed when the admin goes to mark attendance for the said event. The participants are properly stored in the event array and the same function works for the volunteers. Something appears to be broken in the filter function in the Attendance page. That being said the same function works for the volunteers. Further investigation required.

**Comment by nareddyt** [comment]
Reproducible for both `volunteers` and `participants`. Seems to fail intermittently and then work later.

Redux shows volunteers and participants for event `5bc0e2ea07c72404c0697262`. However the UI doesn't show it.

![image.png](https://images.zenhubusercontent.com/587abc0451aa2c3057721b6f/a9d90ec5-fc
0c-496f-b845-3a4fdc4f9e8c)

![image.png](https://images.zenhubusercontent.com/587abc0451aa2c3057721b6f/4d538360-55c5-4d39-af20-8cd02baa2359)

**Comment by nareddyt** [comment]
Seems like there is a discrepancy in redux state in `events.event[14].participants`. The participants key maps to an array of user objects, but the code assumes it is an array of user object IDs. 

Volunteers and participants only see user object IDs, but admins sometime see user object IDs and sometimes full user objects. Need to track down the root cause.
